CREATE TABLE habitats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    biome      VARCHAR(40)                             NOT NULL,
    location   VARCHAR(120)                            NOT NULL,
    min_temp_c INTEGER                                 NOT NULL,
    max_temp_c INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_habitats PRIMARY KEY (id)
);

ALTER TABLE creatures
    ADD CONSTRAINT FK_CREATURES_ON_HABITAT FOREIGN KEY (habitat_id) REFERENCES habitats (id);